### PR TITLE
SXR Unity plugin documentation

### PR DESCRIPTION
**Pull request by nitosan**
* Update documentation for Unity Plugin
* Update Index page

### CODE REVIEW

**Comment by thomasflynn** [comment]
wow, that's a lot of files.  i'll have to cherry-pick and run the website tomorrow.  in the meantime, you should probably add the SXR-DCO?

**Comment by thomasflynn** [comment]
it looks like you checked in a deployed version of the site (in the site/ directory).  was that intended?  you also checked in a bunch of files in a temp/ directory.

**Comment by thomasflynn** [comment]
otherwise, the new organization looks good.  nice job.

**Comment by nitosan** [comment]
Let me remove the generated content

**Pull request merged**
